---
name: GitHub Actions CI/CD
on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches: 
      - souls/development
      - souls/staging
      - souls/production
    paths:
      - 'infrastructure/frontend/**'
      - 'infrastructure/backend/**'
      - 'apps/frontend/**'
      - 'api/serverless/**'

# Using concurrency and the default behavior
concurrency: ci-${{ github.ref }}

jobs:

  # Monitor Customer Portal File Changes
  changes:
    name: Monitor changes
    strategy:
      matrix:
        branches: [souls/development, souls/staging, souls/production]
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          frontend-iac:
            - 'infrastructure/frontend/**'
          frontend-app:
            - 'apps/frontend/**'
          backend-iac:
            - 'infrastructure/backend/**'
          backend-api:
            - 'api/serverless/**'
    - id: target
      if: ${{ matrix.branches == github.event.pull_request.base.ref }}
      run: echo "branch=${{ matrix.branches }}" >> "$GITHUB_OUTPUT"
    outputs:
      frontend-iac: ${{ steps.changes.outputs.frontend-iac }}
      frontend-app: ${{ steps.changes.outputs.frontend-app }}
      backend-iac: ${{ steps.changes.outputs.backend-iac }}
      backend-api: ${{ steps.changes.outputs.backend-api }}
      branch: ${{ steps.target.outputs.branch }}

  # Frontend IaC
  frontend-iac:
    name: 
    needs: changes
    if: |
      github.event.pull_request.base.ref == needs.changes.outputs.branch &&
      needs.changes.outputs.frontend-iac == 'true'  && 
      needs.changes.outputs.frontend-app == 'false' &&
      needs.changes.outputs.backend-iac  == 'false' &&
      needs.changes.outputs.backend-api  == 'false' &&
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
    with:
      directory: infrastructure/frontend/
      environment: ${{ needs.changes.outputs.branch }}
      branch: ${{ needs.changes.outputs.branch }}

  # Frontend APP
  frontend-app:
    name: 
    needs: changes
    if: |
      github.event.pull_request.base.ref == needs.changes.outputs.branch &&
      needs.changes.outputs.frontend-iac == 'false'  && 
      needs.changes.outputs.frontend-app == 'true' &&
      needs.changes.outputs.backend-iac  == 'false' &&
      needs.changes.outputs.backend-api  == 'false' &&
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
    with:
      directory: infrastructure/frontend/
      environment: ${{ needs.changes.outputs.branch }}
      branch: ${{ needs.changes.outputs.branch }}

  # Backend IaC
  backend-iac:
    name: 
    needs: changes
    if: |
      github.event.pull_request.base.ref == needs.changes.outputs.branch &&
      needs.changes.outputs.frontend-iac == 'false'  && 
      needs.changes.outputs.frontend-app == 'false' &&
      needs.changes.outputs.backend-iac  == 'true' &&
      needs.changes.outputs.backend-api  == 'false' &&
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
    with:
      directory: infrastructure/frontend/
      environment: ${{ needs.changes.outputs.branch }}
      branch: ${{ needs.changes.outputs.branch }}

  # Backend API
  backend-api:
    name: 
    needs: changes
    if: |
      github.event.pull_request.base.ref == needs.changes.outputs.branch &&
      needs.changes.outputs.frontend-iac == 'false'  && 
      needs.changes.outputs.frontend-app == 'false' &&
      needs.changes.outputs.backend-iac  == 'false' &&
      needs.changes.outputs.backend-api  == 'true' &&
    uses: ./.github/workflows/terraform.yml
    secrets: inherit
    with:
      directory: infrastructure/frontend/
      environment: ${{ needs.changes.outputs.branch }}
      branch: ${{ needs.changes.outputs.branch }}

