---
name: Terraform
# concurrency: deploy
on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
      environment:
        required: true
        type: string
      branch:
        required: true
        type: string
  workflow_dispatch:

jobs:
  plan:
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.directory }}
    if: |
      ${{ github.event.action == 'opened' || github.event.action == 'synchronize' }} &&
      github.event.pull_request.base.ref == ${{ inputs.branch }}
    environment: ${{ inputs.environment }}
    name: Plan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: echo "Hello Plan"
